# Укажите версию Docker Compose
version: '3.9'

# Контейнеры, составляющие проект
services:
  db:
    image: postgres:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'